### ISSUE TITLE
Filter in grading tab too keen

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#896] opened 2019-08-24 10:06 UTC
The filter function should wait for the user to hit return. Currently, the display of the keystrokes is very laggy because each keystroke leads to a turn-around with the server to get the filtered list of assessments:

<img width="429" alt="Screenshot 2019-08-24 at 5 57 59 PM" src="https://user-images.githubusercontent.com/30220768/63635860-00ab4b80-c69a-11e9-8158-11f9efff7f98.png">

**Comment by Aulud** [comment] 2019-08-25 15:48
Addressed by #897.

**Comment by Aulud** [comment] 2019-08-27 18:33
Reopened as the fix did not fully resolve the issue - some unknown behaviour is likely occurring that cannot be replicated in the development environment.

**Comment by Aulud** [comment] 2019-08-31 17:02
Prof @martin-henz, @geshuming and I have found the cause of the performance issues - we will try to implement a more satisfactory long-term fix.

**Closed** 2019-09-01 10:16 UTC
Labels: Enhancement, important
