### ISSUE TITLE
Path submission possible, and problem with "closed" status of path

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#847] opened 2019-08-14 09:03 UTC
It seems that Path P1A has a submission feature, which fails. Paths are not meant to be submitted, so should we disable to submit function?

**Comment by martin-henz** [comment] 2019-08-14 09:12
Another student writes:

 have just done the Path P1A and tried submitting it through the "Finalize Submission" button, but I received an error pop up saying "something went wrong". When I refreshed the page, it shows that it is closed which can be seen in the picture attached. 

![Capture (2)](https://user-images.githubusercontent.com/30220768/63009222-a26eb380-beb6-11e9-8caf-308570fe8180.PNG)

**Comment by Aulud** [comment] 2019-08-14 19:06
![image](https://user-images.githubusercontent.com/44989315/63047203-88f55800-bf06-11e9-833d-be044385e83e.png)

Hi Prof, @geshuming and I checked out the issue and we have a suspicion for the source of this bug (see above image - it's actually a backend issue). The above image is from testing in the development environment with mocked assessments.

Presently, students have not been assigned their studio group and by extension, their Avenger. When a student finalises an assessment (the above Path would count), the backend first performs a series of checks and then eventually updates the submission status in the database for that student's submission (this closes the assessment for that student, and works as intended). If this succeeds, a notification is created for that student's Avenger, and it is here where the bug occurs.

Since students do not have a studio group yet, the database returns `:nil` for their Avenger - causing the created notification to be malformed with an illegal `User` (the user whom the notification belongs to). This causes the subsequent database query to fail and the server to return HTTP error code 500 (`Internal Server Error`).

I believe the issue should resolve itself when students are assigned to their Groups, but until that is done any student action that triggers a notification creation for their avenger will trigger the bug. In the meantime, we could implement a fix to the backend by adding a series of stricter `:nil` checks.

**Comment by Aulud** [comment] 2019-08-14 19:11
> It seems that Path P1A has a submission feature, which fails. Paths are not meant to be submitted, so should we disable to submit function?

Regarding the submission of Paths, I have looked through the relevant portion in the backend and it seems the backend allows students to finalise their submission for any assessment type (Paths and Contests included). The only difference in behaviour is that bonus XP is only awarded for Missions and Contests.

I personally think there's not much harm allowing students to finalise their Path submissions, although @blackening might be in a better position to advise as he's authoring the programming Paths.

**Comment by geshuming** [comment] 2019-08-15 07:04
Yes. We traced the internal server error in the backend and has a fix ready.

**Comment by geshuming** [comment] 2019-08-16 12:46
This is fixed

**Closed by geshuming** 2019-08-16 12:46 UTC
Labels: _work in progress
