### ISSUE TITLE
Refactor: Move props to react state

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#747] opened 2019-07-18 14:11 UTC
Many props don't belong in redux state. 

- [ ] Assessment related props. Can be compressed into one `IAssessment` prop or moved to react state. Examples: https://github.com/source-academy/cadet-frontend/blob/860d6c0eec092f66e1340c1db42bd284f579edb1/src/reducers/states.ts#L62-L68 and https://github.com/source-academy/cadet-frontend/blob/860d6c0eec092f66e1340c1db42bd284f579edb1/src/reducers/states.ts#L85

- [ ] Same for 'Grading'

- [ ] Consider moving `editorValue` and `output` to react state as well. No point having these props in the redux store if we refetch the values everytime we navigate in and out of the workspace.

- [ ] Same for these 2 props https://github.com/source-academy/cadet-frontend/blob/860d6c0eec092f66e1340c1db42bd284f579edb1/src/reducers/states.ts#L90-L91

- [ ] Reduce reliance of above. I.e. viewing an assessment should not rely on overview data.

**Comment by chownces** [comment] 2021-05-19 08:10
Duplicate of #1555

**Closed by chownces** 2021-05-19 08:10 UTC
Labels: Enhancement, _refactor
