### ISSUE TITLE
From 2018 team post-mortem: Code duplication between student workspace and grader workspace frontend components

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#683] opened 2019-07-07 08:00 UTC

**Comment by martin-henz** [comment] 2019-07-07 08:04
Can anyone comment on this?

**Comment by geshuming** [comment] 2019-07-07 11:00
Need more info.

**Comment by martin-henz** [comment] 2019-07-07 11:28
@thomastanck : Do you remember what this is about?

**Comment by geshuming** [comment] 2019-07-07 11:48
Oh i understand. The source code is very similar for `AssessmentWorkspace` and `GradingWorkspace`. This violates DRY and is very troublesome to maintain.

**Comment by thomastanck** [comment] 2019-07-07 12:10
Yes, thats right. I think one of the previous maintainers was the one who brought this up

**Comment by alcen** [comment] 2019-07-11 14:59
Duplicate of #229

**Comment by angelsl** [comment] 2020-11-07 21:01
Closing in favour of #1555 (duplicate).

**Closed by angelsl** 2020-11-07 21:01 UTC
Labels: Enhancement, _refactor, minor
