### ISSUE TITLE
built frontend cannot be deployed to a folder

### ISSUE THREAD

**Issue by openorclose** [source-academy/cadet-frontend#1115] opened 2020-05-12 14:06 UTC
After `npm run build`, try to open up `index.html` in the `build` folder directly.

This does not work, as the frontend expects all paths to be absolute paths. This makes deploying different version of the frontend to different folders impossible

**Comment by JingYenLoh** [comment] 2020-06-03 18:54
Can you elaborate more on this? What are you trying to achieve? Would you like to be able to deploy to e.g. foo.com/bar?

**Comment by martin-henz** [comment] 2020-06-03 23:07
Yes, frontend should be deployable as subfolder of any site. This will increase the flexibility of use. In the same context it would be good to be able to deploy subfolders such as the textbook or the Source documentation, within the frontend, as discussed with @angelsl .

**Comment by JingYenLoh** [comment] 2020-06-04 06:09
This is by design and documented. One workaround is to [use environment variables](https://create-react-app.dev/docs/deployment/#customizing-environment-variables-for-arbitrary-build-environments). I'd suggest waiting for @angelsl to update dependencies before working on this though, in theory it shouldn't make a difference but in reality I've been bitten by ridiculous things 🙄

**Comment by angelsl** [comment] 2020-11-07 20:42
I'm closing this issue, because we now have a way to have the service worker ignore subfolders, and the first problem is not something we can solve as long as we are using client-side routing.

**Closed by angelsl** 2020-11-07 20:42 UTC
Labels: Enhancement, Proposal, _infrastructure
