### ISSUE TITLE
Should Microsoft Edge be a "supported browser"?

### ISSUE THREAD

**Issue by alcen** [source-academy/cadet-frontend#728] opened 2019-07-16 03:01 UTC
I tested the code editor on Microsoft Edge and it seems with the new Inspector and Env Visualizer features enabled, programs run indefinitely with breakpoints set.

<img width="955" alt="edge" src="https://user-images.githubusercontent.com/49450743/61262716-cd32f280-a7b8-11e9-82c9-dca3c9bd9910.png">

The editor works fine otherwise.

Perhaps we should just advise students to use Chrome? Maybe add a footer "This website is best viewed in Google Chrome"

**Comment by alcen** [comment] 2019-07-16 03:37
Seems like this only affects older versions of Microsoft Edge (specifically version 42). Tested it on version 44 and it works fine.

**Comment by jiachen247** [comment] 2019-07-29 06:43
The real question is why are you using edge HAHA

**Comment by martin-henz** [comment] 2019-07-29 06:50
Yes, regarding browsers, we've been saying that we prefer students to use Chrome, but it may be time to loosen this a little bit. Edge seems quite good
https://kangax.github.io/compat-table/es6/

But yes, looking at browser support may be a bit premature, and recommending Chrome is probably prudent for the coming semester. We should look at browser support when we look at mobile support. Probably in a CP3108 project in 2020.

I'll make a suggestion for how to communicate our browser support in a Frontend Issue.

**Comment by geshuming** [comment] 2019-07-29 06:59
Shouldn't edge be fine? The only browser we (and many others) can skip support is probably Internet Explorer

**Comment by jiachen247** [comment] 2019-07-29 07:06
Yes I dont think we currently support older versions of IE! but yes im hopeful for Edge in the future after taking on the Chromium engine! Shall we close this for now?

**Comment by alcen** [comment] 2019-07-29 07:20
> The real question is why are you using edge HAHA

Haha, well it is the default browser for Windows if you can't be bothered to install another

**Comment by martin-henz** [comment] 2019-07-31 07:21
@alcen Edge seems to be a decent browser. Do you think we can upgrade it to be a "supported" browser, like Chrome and Firefox? After upgrading your Edge, do you see any issues?

**Comment by alcen** [comment] 2019-07-31 08:32
> @alcen Edge seems to be a decent browser. Do you think we can upgrade it to be a "supported" browser, like Chrome and Firefox? After upgrading your Edge, do you see any issues?

So far, no issues on version 44 with the deployed version

In fact the Env Visualiser (which still doesn't show on Firefox) works alright on Edge!

**Comment by geshuming** [comment] 2019-07-31 08:53
Generally speaking we support whatever React supports, which should be all popular browsers.

Internet explorer has an issue where it could not evaluate arrow syntax i.e. `x => x`. More on [here](https://caniuse.com/#feat=arrow-functions)

Other than that, we also have to be careful with external libraries and dependencies that we are using, but i think they should all work.

**Comment by martin-henz** [comment] 2019-07-31 09:59
OK. Maybe we can fine-tune the wording a bit, in the future. For now, I guess it's ok to "officially" support Firefox and Chrome and silently support Edge and whatnot. Let's see what issues come up during the semester.

I hope we can take a closer look at mobile-friendliness in CP3108, but that's more of a UI design issue.

**Comment by martin-henz** [comment] 2019-07-31 10:02
> Internet explorer has an issue where it could not evaluate arrow syntax i.e. `x => x`. More on [here](https://caniuse.com/#feat=arrow-functions)

Oh, that means IE is dead and we shouldn't waste any breath talking about it.

**Comment by anthony-halim** [comment] 2020-08-16 15:01
Closing this issue, Edge is now based on Chromium engine. Unable to reproduce the issue from the example.

**Closed by anthony-halim** 2020-08-16 15:01 UTC
Labels: Question, minor
