### ISSUE TITLE
Source Academy currently starts with errors!

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#757] opened 2019-07-21 10:12 UTC
Visiting 
https://sourceacademy.nus.edu.sg
gives:

<img width="1085" alt="Screenshot 2019-07-21 at 6 10 15 PM" src="https://user-images.githubusercontent.com/30220768/61589876-fd2c2c80-abe2-11e9-958d-2e0e9460b319.png">

**Comment by rrtheonlyone** [comment] 2019-07-21 23:04
I am not able to reproduce this error. Do you still see it?

**Comment by geshuming** [comment] 2019-07-22 05:08
This is an old issue #666 that isn't fixed yet.

**Comment by rrtheonlyone** [comment] 2019-07-22 11:06
That only applies for local development, I dont recall seeing it in the production site.

**Comment by geshuming** [comment] 2019-07-22 11:15
It doesn't always happen though, and it doesn't crash Source Academy.

**Comment by jiachen247** [comment] 2019-07-29 06:41
a MCVE for this issue would be helpful to reproduce this error if not we should close the issue for now!

**Comment by martin-henz** [comment] 2019-07-29 08:05
Here is a CVE (not sure how minimal):
Start Chrome 75 on Macbook Pro running MacOS Mojave, by clicking here:
https://sourceacademy.nus.edu.sg/playground#chap=4&ext=SOUNDS&prgrm=A4GwhgngFMYJYCcoBcAEBeAfKgtmZAFgPoDOcAdiqgFSoBMNu%2BxACgJKMAcADNwJQAaenz4BuIA
Then you get this in the JavaScript console of Chrome:

playground#chap=4&ext=SOUNDS&prgrm=A4GwhgngFMYJYCcoBcAEBeAfKgtmZAFgPoDOcAdiqgFSoBMNu%2BxACgJKMAcADNwJQAaenz4BuIA:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by geshuming** [comment] 2019-07-29 08:24
I don't think this is the same issue.

But for MCVE, try loading https://sourceacademy.nus.edu.sg/academy/game or on local deployment, 
localhost:8075/academy/game

I suspect it has something to do with the error 401 response 
![image](https://user-images.githubusercontent.com/43642522/62032849-443aa300-b21d-11e9-8b82-c4e8ea0c2b47.png)

**Comment by martin-henz** [comment] 2019-07-29 08:38
So to summarise: We have various unexplained 404 and 401 responses in the JavaScript console, none of which have any known problematic consequences. So I'll reduce the severity to "important". I think it's important to follow up, because the 404/401 are probably symptoms of deeper issues.

**Comment by jiachen247** [comment] 2019-07-29 09:25
Hmmm can I check if the `USE_BACKEND` flag in `.env` turned on or off?

**Comment by martin-henz** [comment] 2019-07-29 09:30
> Hmmm can I check if the `USE_BACKEND` flag in `.env` turned on or off?

Don't get the question. I'm referring to the production system. The user is not setting any flags. So the answer: Whatever flags the deployment sets.

**Comment by geshuming** [comment] 2019-07-29 09:45
> Hmmm can I check if the `USE_BACKEND` flag in `.env` turned on or off?

It seems like the frontend will attempt a "backend" call even when you don't use backend

**Comment by geshuming** [comment] 2019-07-29 09:53
Here's the issue for the backend call when `USE_BACKEND` is FALSE

https://github.com/source-academy/cadet-frontend/blob/55e38385275f2dc95a3940dd22053d69dc32b439/src/components/academy/game/index.tsx#L6

And this call here may lead to 401 responses, which returns a null object, hence the null error

https://github.com/source-academy/cadet-frontend/blob/55e38385275f2dc95a3940dd22053d69dc32b439/src/components/academy/game/index.tsx#L70-L76

**Closed** 2019-07-30 04:00 UTC
Labels: Bug, important
