### ISSUE TITLE
INSPECT crashes frontend

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#983] opened 2019-11-04 12:35 UTC
Enter in editor (Source §3) the following program and hit Run:

```
function f(x) {
    const a = x * 2;
    return a;
}

map(f, list(1,2,3));
```

* set breakpoint on "return a;"
* click on INSPECT
* enter "x;" in REPL
* enter "a;" in REPL
* click Run

This crashes the frontend:

<img width="747" alt="Screenshot 2019-11-05 at 7 41 42 AM" src="https://user-images.githubusercontent.com/30220768/68167619-0a5a0500-ffa1-11e9-93a8-d75bf300a8a1.png">

**Comment by martin-henz** [comment] 2019-11-04 23:43
Clicking on Run after that crashes the frontend:

<img width="747" alt="Screenshot 2019-11-05 at 7 41 42 AM" src="https://user-images.githubusercontent.com/30220768/68167263-e3e79a00-ff9f-11e9-8720-3e6b1266dd52.png">

**Comment by Aulud** [comment] 2019-11-13 13:34
@martin-henz @blackening has a workaround to prevent the problem crashing the interpreter on the frontend in PR #865. A thorough fix would however require rewriting the offending script to (1) preferably avoid accessing HTML elements directly on the page and (2) if so, employ proper guards to prevent undefined behaviour.

**Comment by martin-henz** [comment] 2019-11-13 13:41
Thanks! This is not mission critical. We don't want to make changes on the Academy this close to the PA, unless it's necessary for actually conducting the PA.

**Comment by podocarp** [comment] 2020-05-16 09:39
It is fairly easy to fix the JS errors in the screenshots above, that was from a careless guard condition. However after fixing them, and performing the same steps you get the error in the REPL: `Line 33: Name xs not declared.`. `xs` here must be from `map`. It would seem like this is a regression. Now evaluating in the REPL after pausing at a breakpoint wipes out the old context.

**Comment by podocarp** [comment] 2020-05-16 13:00
The JS errors are quite easily fixed, it is caused by a poor guard statement and I have a new branch to fix it. However it only exposes another problem.

Same program, but with `for_each` instead because it's cleaner. Same way of pausing, and executing on the REPL. This is before executing on the REPL. All OK, and if we don't execute anything on the REPL, you will be able to step through till the end like this.
![2020-05-16-205355_620x545_scrot](https://user-images.githubusercontent.com/10473184/82120314-9f219480-9774-11ea-920f-6b30046bf3ca.png)

After executing on the REPL this happens.
![2020-05-16-205552_481x574_scrot](https://user-images.githubusercontent.com/10473184/82120312-9df06780-9774-11ea-9c81-a51b0023e155.png)

I have been out of the loop for some time so I am not sure why this is occuring. The inspector caches a copy of the paused state when the interpreter hits the breakpoint. It is this saved state that is drawn by the visualizer. I am not sure why this state is being changed and am also not sure where it is being changed from, hopefully someone else will be able to solve this.

**Comment by martin-henz** [comment] 2020-05-16 13:12
This is the old env viz. Can you try branch sa_2021?

**Comment by angelsl** [comment] 2020-11-07 20:46
The issue described initially no longer occurs. I suppose the environment visualiser will be revamped anyway, so I will close this issue.

**Closed by angelsl** 2020-11-07 20:46 UTC
Labels: Bug, critical, important
